const fsLibrary = require('fs');

let sources = {
  "source145" : {
    "android_scheme" : "hbogo",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hbo_go_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/hbo-go\/id429775439",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.HBO",
    "ios_scheme" : "hbogo",
    "type" : "tve",
    "name" : "HBO GO",
    "regions" : [
      "US"
    ]
  },
  "source420" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/420_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "HiDive",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source91" : {
    "android_scheme" : "discovery-go",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/discovery_go_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id1039067950",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.discovery.discoverygo",
    "ios_scheme" : "dsc-go",
    "type" : "tve",
    "name" : "Discovery GO",
    "regions" : [
      "US"
    ]
  },
  "source170" : {
    "android_scheme" : "lifetimeplus",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/lifetime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/lifetime\/id579966222",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.aetn.lifetime.watch",
    "ios_scheme" : "lifetimeplus",
    "type" : "free",
    "name" : "Lifetime",
    "regions" : [
      "US"
    ]
  },
  "source356" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/disney_now_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/disneynow-shows-live-tv\/id529997671",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.disney.datg.videoplatforms.android.watchdc",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "DisneyNOW",
    "regions" : [
      "US"
    ]
  },
  "source381" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/funimation_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/funimation\/id1075603018",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.Funimation.FunimationNow",
    "ios_scheme" : "funi",
    "type" : "sub",
    "name" : "Funimation",
    "regions" : [
      "AU",
      "US",
      "GB"
    ]
  },
  "source148" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/history_vault_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "HISTORY Vault (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source215" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/pbs_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/pbs-video\/id398349296",
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "PBS",
    "regions" : [
      "US"
    ]
  },
  "source384" : {
    "android_scheme" : "hulu",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/384_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "hulu",
    "type" : "sub",
    "name" : "Cinemax (Via Hulu)",
    "regions" : [
      "US"
    ]
  },
  "source387" : {
    "android_scheme" : "hbomax",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hbomax_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "hbomax",
    "type" : "sub",
    "name" : "HBO MAX",
    "regions" : [
      "US"
    ]
  },
  "source102" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/dove_channel_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Dove Channel (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source8" : {
    "android_scheme" : "aetvplus",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/ae_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/a-e\/id571711580",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.aetn.aetv.watch",
    "ios_scheme" : "aetvplus",
    "type" : "tve",
    "name" : "A&E",
    "regions" : [
      "US"
    ]
  },
  "source179" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/mtv_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/mtv\/id422366403",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.mtvn.mtvPrimeAndroid",
    "ios_scheme" : "mtvnetworkapp",
    "type" : "free",
    "name" : "MTV",
    "regions" : [
      "US"
    ]
  },
  "source271" : {
    "android_scheme" : "syfytve",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/syfy_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/syfy-now\/id378092432",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.nbcu.tve.syfy",
    "ios_scheme" : "syfytve",
    "type" : "free",
    "name" : "Syfy",
    "regions" : [
      "US"
    ]
  },
  "source12" : {
    "android_scheme" : "ahc-go",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/ahc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id1111279987",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.discovery.ahcgo",
    "ios_scheme" : "ahc-go",
    "type" : "tve",
    "name" : "AHC GO",
    "regions" : [
      "US"
    ]
  },
  "source246" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/shout_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Shout! Factory TV",
    "regions" : [
      "US"
    ]
  },
  "source313" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/vimeo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/vimeo\/id425194759",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.vimeo.android.videoapp",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Vimeo",
    "regions" : [
      "US"
    ]
  },
  "source249" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/showtime_amazon_prime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Showtime (via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source274" : {
    "android_scheme" : "tlc-go",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/tlcgo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id1101436320",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.discovery.tlcgo",
    "ios_scheme" : "tlc-go",
    "type" : "tve",
    "name" : "TLC GO",
    "regions" : [
      "US"
    ]
  },
  "source108" : {
    "android_scheme" : "epix",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/epix_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/epix\/id430018488",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.epix.epix",
    "ios_scheme" : "epixnow",
    "type" : "tve",
    "name" : "EPIX",
    "regions" : [
      "US"
    ]
  },
  "source18" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/acorn_tv_prime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv-uk",
    "type" : "sub",
    "name" : "Acorn TV (Via Amazon Prime)",
    "regions" : [
      "US",
      "CA",
      "GB"
    ]
  },
  "source277" : {
    "android_scheme" : "tvlandnetworkapp",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/tvland_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/us\/app\/tv-land\/id1065978080",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.vmn.playplex.tvland",
    "ios_scheme" : "tvlandnetworkapp",
    "type" : "tve",
    "name" : "TV Land",
    "regions" : [
      "US"
    ]
  },
  "source46" : {
    "android_scheme" : "bravotve",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/bravo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/bravo-now\/id383925190",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.nbcu.tve.bravo",
    "ios_scheme" : "bravotve",
    "type" : "tve",
    "name" : "Bravo",
    "regions" : [
      "US"
    ]
  },
  "source71" : {
    "android_scheme" : "ccnetworkapp",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/comedy-central\/id799551807",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.vmn.android.comedycentral",
    "ios_scheme" : "ccnetworkapp",
    "type" : "free",
    "name" : "Comedy Central",
    "regions" : [
      "US"
    ]
  },
  "source344" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/youtube_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/youtube\/id544007664",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.google.android.youtube",
    "ios_scheme" : "youtube",
    "type" : "purchase",
    "name" : "YouTube",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source203" : {
    "android_scheme" : "nflx",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/netflix_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/netflix\/id363590051",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.netflix.mediaclient&hl=en",
    "ios_scheme" : "nflx",
    "type" : "sub",
    "name" : "Netflix",
    "regions" : [
      "GB",
      "CA",
      "US",
      "AU"
    ]
  },
  "source372" : {
    "android_scheme" : "disneyplus",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/disneyPlus_100px.png",
    "ios_appstore_url" : "https:\/\/apps.apple.com\/app\/disney\/id1446075923",
    "android_playstore_url" : null,
    "ios_scheme" : "disneyplus",
    "type" : "sub",
    "name" : "Disney+",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source347" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fyi_logo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/fyi-tv\/id887597381",
    "android_playstore_url" : null,
    "ios_scheme" : "fyiplus",
    "type" : "free",
    "name" : "fyi",
    "regions" : [
      "US"
    ]
  },
  "source414" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/414_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "pantaflix",
    "type" : "purchase",
    "name" : "Pantaflix",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source77" : {
    "android_scheme" : "crackle",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/sony_crackle_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/crackle-movies-tv\/id377951542",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.gotv.crackle.handset",
    "ios_scheme" : "crackle",
    "type" : "free",
    "name" : "Crackle",
    "regions" : [
      "US"
    ]
  },
  "source206" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/nick_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/nick\/id596133590",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.nickonline.android.nickapp",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "Nickelodeon",
    "regions" : [
      "US"
    ]
  },
  "source231" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/starz_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/starz-play\/id550221096",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.bydeluxe.d3.android.program.starz",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "STARZ",
    "regions" : [
      "US"
    ]
  },
  "source375" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/epixPrimeVideo_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Epix (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source192" : {
    "android_scheme" : "nbctve",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/nbc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/nbc\/id442839435",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.nbcuni.nbc",
    "ios_scheme" : "nbctve",
    "type" : "tve",
    "name" : "NBC",
    "regions" : [
      "US"
    ]
  },
  "source442" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/442_autogenerated.png",
    "ios_appstore_url" : "https:\/\/apps.apple.com\/app\/directv\/id307386350",
    "android_playstore_url" : null,
    "ios_scheme" : "directv",
    "type" : "sub",
    "name" : "DirecTV On Demand",
    "regions" : [
      "US"
    ]
  },
  "source234" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/starz_amazon_prime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "STARZ (Via Amazon Prime)",
    "regions" : [
      "US",
      "GB"
    ]
  },
  "source301" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/umc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Urban Movie Channel (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source378" : {
    "android_scheme" : "amcmobileapp",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/amcPremiere_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amc-stream-tv-shows-movies\/id1025120568",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.amctve.amcfullepisodes",
    "ios_scheme" : "amcmobileapp",
    "type" : "sub",
    "name" : "AMC Premiere",
    "regions" : [
      "US"
    ]
  },
  "source445" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/445_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "Discovery+",
    "regions" : [
      "US"
    ]
  },
  "source195" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/universo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/nbc-universo-now\/id869444353",
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "NBC UNIVERSO",
    "regions" : [
      "US"
    ]
  },
  "source237" : {
    "android_scheme" : "sci-go",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/scigo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id1111281685",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.discovery.scigo",
    "ios_scheme" : "sci-go",
    "type" : "tve",
    "name" : "Science GO",
    "regions" : [
      "US"
    ]
  },
  "source20" : {
    "android_scheme" : "adultswim",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/adultswim_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/adult-swim\/id417871100",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.adultswim.videoapp.android",
    "ios_scheme" : "adultswim",
    "type" : "tve",
    "name" : "Adult Swim",
    "regions" : [
      "US"
    ]
  },
  "source198" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/natgeo_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "National Geographic",
    "regions" : [
      "US"
    ]
  },
  "source307" : {
    "android_scheme" : "vuduapp",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/vudu_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/vudu-player-movies-tv\/id487285735",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=air.com.vudu.air.DownloaderTablet",
    "ios_scheme" : "vuduapp",
    "type" : "purchase",
    "name" : "VUDU",
    "regions" : [
      "US"
    ]
  },
  "source332" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/tcm_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/watch-tcm\/id341161319",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.tcm.tcm",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "Watch TCM",
    "regions" : [
      "US"
    ]
  },
  "source124" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fandangoNow_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/m-go-movies-+-tv\/id738201550",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.mgo.application",
    "ios_scheme" : null,
    "type" : "purchase",
    "name" : "FandangoNOW",
    "regions" : [
      "US"
    ]
  },
  "source26" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/prime_video_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id545519333",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Amazon Prime",
    "regions" : [
      "US",
      "GB",
      "CA",
      "AU"
    ]
  },
  "source293" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/tribeca_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/tribeca-shortlist\/id993038295",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.tribeca.shortlist",
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "Tribeca Shortlist",
    "regions" : [
      "US"
    ]
  },
  "source268" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/sundance_now_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/sundancenow-doc-club-documentaries\/id879902807",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.dramafever.docclub",
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "SundanceNow Doc Club",
    "regions" : [
      "US"
    ]
  },
  "source54" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cmt_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/cmt-app\/id730993656",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.mtvn.cmtandroid",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "CMT",
    "regions" : [
      "US"
    ]
  },
  "source152" : {
    "android_scheme" : "hmnow",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hallmark_movies_now_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/feeln-movies-together\/id472567577",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.feeln.android",
    "ios_scheme" : "com.spiritclips.sc",
    "type" : "sub",
    "name" : "Hallmark Movies Now",
    "regions" : [
      "US"
    ]
  },
  "source296" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/tubi_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/tubi-tv-watch-free-movies\/id886445756",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.tubitv",
    "ios_scheme" : "tubitv",
    "type" : "free",
    "name" : "Tubi TV",
    "regions" : [
      "US",
      "AU",
      "CA"
    ]
  },
  "source57" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cnbc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/cnbc-business-news-finance\/id398018310",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.cnbc.client",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "CNBC",
    "regions" : [
      "US"
    ]
  },
  "source82" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/diy_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "DIY",
    "regions" : [
      "US"
    ]
  },
  "source405" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/405_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "Darkmatter TV",
    "regions" : [
      "CA",
      "US"
    ]
  },
  "source299" : {
    "android_scheme" : "usatve",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/usa_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/usa-now\/id661695783",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.usanetwork.watcher",
    "ios_scheme" : "usatve",
    "type" : "tve",
    "name" : "USA",
    "regions" : [
      "US"
    ]
  },
  "source366" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/criterion_100px.png",
    "ios_appstore_url" : "http:\/\/apps.apple.com\/app\/the-criterion-channel\/id1454275199",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.criterionchannel",
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "The Criterion Channel",
    "regions" : [
      "US",
      "CA"
    ]
  },
  "source391" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/391_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Pluto TV",
    "regions" : [
      "US",
      "GB"
    ]
  },
  "source433" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/433_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "Sun Nxt",
    "regions" : [
      "US",
      "CA",
      "AU"
    ]
  },
  "source250" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/showtime_anytime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id484232467",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.showtime.showtimeanytime",
    "ios_scheme" : "shoany",
    "type" : "tve",
    "name" : "Showtime Anytime",
    "regions" : [
      "US"
    ]
  },
  "source225" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/popcornflix_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/popcornflix-free-movies\/id493605531",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.curiousbrain.popcornflix",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Popcornflix",
    "regions" : [
      "US",
      "CA"
    ]
  },
  "source369" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/youtubePremium_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/youtube\/id544007664",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.google.android.youtube",
    "ios_scheme" : "youtube",
    "type" : "free",
    "name" : "Youtube Premium",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source253" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/shudder_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Shudder (Via Amazon Prime)",
    "regions" : [
      "US",
      "GB",
      "CA"
    ]
  },
  "source439" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/439_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Plex",
    "regions" : [
      "US"
    ]
  },
  "source256" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/smithsonian_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Smithsonian Earth (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source140" : {
    "android_scheme" : "3CBMKWkagp_Y97R_Qfm-fQ",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/googlePlay_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : "https:\/\/play.google.com\/store",
    "ios_scheme" : null,
    "type" : "purchase",
    "name" : "Google Play",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source115" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fox_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/fox-now\/id571096102",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.fox.now",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "FOX",
    "regions" : [
      "US"
    ]
  },
  "source34" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/bet_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/bet-now-watch-shows\/id841118013",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.bet.shows",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "BET",
    "regions" : [
      "US"
    ]
  },
  "source284" : {
    "android_scheme" : "cwtv",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cw_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/the-cw-network\/id491730359",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.cw.fullepisodes.android",
    "ios_scheme" : "cwtv",
    "type" : "free",
    "name" : "The CW",
    "regions" : [
      "US"
    ]
  },
  "source259" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/sps_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "South Park Studios",
    "regions" : [
      "US"
    ]
  },
  "source62" : {
    "android_scheme" : "cartoonnetwork",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cn_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/watch-cartoon-network-videos\/id404593641",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.turner.cnvideoapp",
    "ios_scheme" : "cartoonnetwork",
    "type" : "tve",
    "name" : "Cartoon Network",
    "regions" : [
      "US"
    ]
  },
  "source287" : {
    "android_scheme" : "historyplus",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/history_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/history\/id576009463",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.aetn.history.watch",
    "ios_scheme" : "historyplus",
    "type" : "tve",
    "name" : "The History Channel",
    "regions" : [
      "US"
    ]
  },
  "source146" : {
    "android_scheme" : "hbonow",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hbo_now_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/hbo-now\/id971265422",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.hbo.hbonow",
    "ios_scheme" : "hbomax",
    "type" : "sub",
    "name" : "HBO NOW",
    "regions" : [
      "US"
    ]
  },
  "source421" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/421_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "curiositystream",
    "type" : "sub",
    "name" : "Curiosity Stream",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source171" : {
    "android_scheme" : "lifetimeplus",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/lifetime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/lifetime\/id579966222",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.aetn.lifetime.watch",
    "ios_scheme" : "lifetimeplus",
    "type" : "tve",
    "name" : "Lifetime",
    "regions" : [
      "US"
    ]
  },
  "source68" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cinemax_prime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Cinemax (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source93" : {
    "android_scheme" : "dlf-go",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/discover_life_go_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id1111281680",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.discovery.dlfgo",
    "ios_scheme" : "dlf-go",
    "type" : "tve",
    "name" : "Discovery Life GO",
    "regions" : [
      "US"
    ]
  },
  "source357" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/boomerang_prime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Boomerang (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source382" : {
    "android_scheme" : "betplus",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/betplus_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id1456618978",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.viacom.betplus",
    "ios_scheme" : "betplus",
    "type" : "sub",
    "name" : "BET+",
    "regions" : [
      "US"
    ]
  },
  "source174" : {
    "android_scheme" : "maxgo",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/maxgo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/max-go\/id453560335",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.MAXGo",
    "ios_scheme" : "maxgo",
    "type" : "tve",
    "name" : "MAX GO",
    "regions" : [
      "US"
    ]
  },
  "source96" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/disney_junior_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Disney Junior",
    "regions" : [
      "US"
    ]
  },
  "source216" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/pbs_kids_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "PBS KIDS (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source149" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hln_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/hln-to-go\/id945045501",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.hln.mobile.hlnApp",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "HLN",
    "regions" : [
      "US"
    ]
  },
  "source385" : {
    "android_scheme" : "hulu",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/385_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "hulu",
    "type" : "sub",
    "name" : "HBO (Via Hulu)",
    "regions" : [
      "US"
    ]
  },
  "source6" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/60minutes_all_access_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "60 Minutes All Access",
    "regions" : [
      "US"
    ]
  },
  "source311" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/verizon_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "purchase",
    "name" : "Verizon On Demand",
    "regions" : [
      "US"
    ]
  },
  "source388" : {
    "android_scheme" : "peacock",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/peacock_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "peacock",
    "type" : "free",
    "name" : "Peacock",
    "regions" : [
      "US"
    ]
  },
  "source103" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/103_autogenerated.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Dox (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source9" : {
    "android_scheme" : "abcplayer",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/abc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/abc-player\/id364191819",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.disney.datg.videoplatforms.android.abc",
    "ios_scheme" : "abcplayer",
    "type" : "free",
    "name" : "ABC",
    "regions" : [
      "US"
    ]
  },
  "source247" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/shout_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Shout! Factory TV (Via Amazon Prime)",
    "regions" : [
      "US",
      "GB"
    ]
  },
  "source272" : {
    "android_scheme" : "watchtbs",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/tbs_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/watch-tbs\/id462780547",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.turner.tbs.android.networkapp",
    "ios_scheme" : "watchtbs",
    "type" : "tve",
    "name" : "TBS",
    "regions" : [
      "US"
    ]
  },
  "source131" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/foodnet_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Food Network",
    "regions" : [
      "US"
    ]
  },
  "source17" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/acorn_tv_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/acorn-tv\/id896014310",
    "android_playstore_url" : null,
    "ios_scheme" : "acorn",
    "type" : "sub",
    "name" : "Acorn TV",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source342" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/yahoo_view_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Yahoo View",
    "regions" : [
      "US"
    ]
  },
  "source134" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fod_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/funny-or-die\/id299546679",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.funnyordie.videos",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Funny or Die",
    "regions" : [
      "US"
    ]
  },
  "source201" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/natgeo_kids_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "National Geographic Kids",
    "regions" : [
      "US"
    ]
  },
  "source278" : {
    "android_scheme" : "tvlandnetworkapp",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/tvland_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/us\/app\/tv-land\/id1065978080",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.vmn.playplex.tvland",
    "ios_scheme" : "tvlandnetworkapp",
    "type" : "free",
    "name" : "TV Land",
    "regions" : [
      "US"
    ]
  },
  "source345" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/youtube_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/youtube\/id544007664",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.google.android.youtube",
    "ios_scheme" : "youtube",
    "type" : "free",
    "name" : "YouTube",
    "regions" : [
      "US",
      "AU"
    ]
  },
  "source73" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cc_now_prime_video_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Comedy Central Stand-Up Plus (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source162" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/indie_flx_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id919741804",
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "IndieFlix",
    "regions" : [
      "US"
    ]
  },
  "source204" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/nickjr_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/nick-jr.\/id911115712",
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Nick Jr.",
    "regions" : [
      "US"
    ]
  },
  "source373" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fuboTV_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "fuboTV",
    "regions" : [
      "US"
    ]
  },
  "source348" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fyi_logo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/fyi-tv\/id887597381",
    "android_playstore_url" : null,
    "ios_scheme" : "fyiplus",
    "type" : "tve",
    "name" : "fyi",
    "regions" : [
      "US"
    ]
  },
  "source440" : {
    "android_scheme" : "nflx",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/netflixFree_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/netflix\/id363590051",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.netflix.mediaclient&hl=en",
    "ios_scheme" : "nflx",
    "type" : "free",
    "name" : "Netflix Free",
    "regions" : [
      "US"
    ]
  },
  "source165" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/165_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "ids-go",
    "type" : "free",
    "name" : "Investigation Discovery",
    "regions" : [
      "US"
    ]
  },
  "source232" : {
    "android_scheme" : "starz",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/starz_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/starz-play\/id550221096",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.bydeluxe.d3.android.program.starz",
    "ios_scheme" : "starz",
    "type" : "sub",
    "name" : "STARZ",
    "regions" : [
      "US"
    ]
  },
  "source79" : {
    "android_scheme" : "crunchyroll",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/crunchyroll_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/crunchyroll-watch-anime-drama\/id329913454",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.crunchyroll.crunchyroid",
    "ios_scheme" : "crunchyroll",
    "type" : "free",
    "name" : "Crunchyroll",
    "regions" : [
      "US"
    ]
  },
  "source207" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/nick_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/nick\/id596133590",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.nickonline.android.nickapp",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Nickelodeon",
    "regions" : [
      "US"
    ]
  },
  "source376" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/britbox_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "Britbox",
    "regions" : [
      "GB",
      "AU",
      "US",
      "CA"
    ]
  },
  "source443" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/443_autogenerated.png",
    "ios_appstore_url" : "https:\/\/apps.apple.com\/app\/spectrum-tv\/id420455839",
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "Spectrum On Demand",
    "regions" : [
      "US"
    ]
  },
  "source168" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/logo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/logotv\/id795019155",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.mtvn.logoandroid",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "LOGO",
    "regions" : [
      "US"
    ]
  },
  "source193" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/nbc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/nbc-news\/id319740707",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.zumobi.msnbc",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "NBC News",
    "regions" : [
      "US"
    ]
  },
  "source302" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/vh1_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/vh1\/id413522634",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.mtvn.vh1android",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "VH1",
    "regions" : [
      "US"
    ]
  },
  "source379" : {
    "android_scheme" : "epixnow",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/epixNow_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/epix-now\/id1387514950",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.epix.epix.now",
    "ios_scheme" : "epixnow",
    "type" : "sub",
    "name" : "Epix Now",
    "regions" : [
      "US"
    ]
  },
  "source196" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/natgeo_wild100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Nat Geo Wild",
    "regions" : [
      "US"
    ]
  },
  "source238" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/screambox_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Screambox (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source305" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/viceland_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/viceland\/id1075922366",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.vice.viceland",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "VICELAND",
    "regions" : [
      "US"
    ]
  },
  "source330" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/foodnet_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/watch-food-network\/id642410271",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.foodnetwork.watcher",
    "ios_scheme" : "food-go",
    "type" : "tve",
    "name" : "Watch Food Network",
    "regions" : [
      "US"
    ]
  },
  "source122" : {
    "android_scheme" : "x-fxnow",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fx_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/fxnow\/id767268733",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.fxnetworks.fxnow",
    "ios_scheme" : "x-fxnow",
    "type" : "tve",
    "name" : "FX",
    "regions" : [
      "US"
    ]
  },
  "source199" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/natgeo_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "National Geographic",
    "regions" : [
      "US"
    ]
  },
  "source50" : {
    "android_scheme" : "cbs",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cbs_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/cbs\/id530168168",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.cbs.app",
    "ios_scheme" : "cbstve",
    "type" : "free",
    "name" : "CBS",
    "regions" : [
      "US"
    ]
  },
  "source308" : {
    "android_scheme" : "vuduapp",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/vudu_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/vudu-player-movies-tv\/id487285735",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=air.com.vudu.air.DownloaderTablet",
    "ios_scheme" : "vuduapp",
    "type" : "free",
    "name" : "VUDU",
    "regions" : [
      "US"
    ]
  },
  "source333" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/trvl_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/watch-travel-channel\/id596546023",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.travelchannel.watcher",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "Watch Travel Channel",
    "regions" : [
      "US"
    ]
  },
  "source125" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fandor_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/fandor-movies-watch-only-great\/id474930762",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.fandor.android",
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "Fandor",
    "regions" : [
      "US",
      "CA"
    ]
  },
  "source150" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hln_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/hln-to-go\/id945045501",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.hln.mobile.hlnApp",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "HLN",
    "regions" : [
      "US"
    ]
  },
  "source53" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cbs_news_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/cbs-news\/id334256223",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.treemolabs.apps.cbsnews",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "CBS News",
    "regions" : [
      "US"
    ]
  },
  "source269" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/sundance_now_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "SundanceNow Doc Club (Via Amazon Prime)",
    "regions" : [
      "CA",
      "GB",
      "US"
    ]
  },
  "source294" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/tribeca_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Tribeca Shortlist (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source361" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/freeform_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/abc-family\/id505728417",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.disney.datg.videoplatforms.android.abcf",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Freeform",
    "regions" : [
      "US"
    ]
  },
  "source81" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/curiosity_stream_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Curiosity Stream (Via Amazon Prime)",
    "regions" : [
      "US",
      "GB"
    ]
  },
  "source56" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cnbc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/cnbc-business-news-finance\/id398018310",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.cnbc.client",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "CNBC",
    "regions" : [
      "US"
    ]
  },
  "source364" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/facebook_watch_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Facebook Watch",
    "regions" : [
      "US"
    ]
  },
  "source84" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/daring_docs_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Daring Docs (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source181" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/mubi_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/mubi\/id626148774",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.mubi",
    "ios_scheme" : "mubi",
    "type" : "sub",
    "name" : "MUBI",
    "regions" : [
      "GB",
      "AU",
      "US",
      "CA"
    ]
  },
  "source367" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/kanopy_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/kanopy\/id1205614510",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.kanopy",
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "Kanopy",
    "regions" : [
      "US",
      "AU"
    ]
  },
  "source159" : {
    "android_scheme" : "hulu",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hulu_showtime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/hulu-plus\/id376510438",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.hulu.plus",
    "ios_scheme" : "hulu",
    "type" : "sub",
    "name" : "Hulu with Showtime",
    "regions" : [
      "US"
    ]
  },
  "source251" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/showtime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/showtime-anytime\/id484232467",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.showtime.showtimeanytime",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Showtime FREEview",
    "regions" : [
      "US"
    ]
  },
  "source321" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cooking_channel_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/watch-cooking-channel\/id675276583",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.cookingchannel.watcher",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "Watch Cooking Channel",
    "regions" : [
      "US"
    ]
  },
  "source398" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/398_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "purchase",
    "name" : "Microsoft Store",
    "regions" : [
      "US",
      "GB",
      "AU",
      "CA"
    ]
  },
  "source30" : {
    "android_scheme" : "apl-go",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/apgo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id1101434093",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.discovery.aplgo",
    "ios_scheme" : "apl-go",
    "type" : "tve",
    "name" : "Animal Planet GO",
    "regions" : [
      "US"
    ]
  },
  "source257" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/snagfilms_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/snagfilms-watch-free-movies\/id404906625",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=air.com.snagfilms",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "SnagFilms",
    "regions" : [
      "US"
    ]
  },
  "source282" : {
    "android_scheme" : "telemundotve",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/telemundo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/telemundo-now\/id680595680",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.telemundo.awe",
    "ios_scheme" : "telemundotve",
    "type" : "tve",
    "name" : "Telemundo Now",
    "regions" : [
      "US"
    ]
  },
  "source61" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cw_seed_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "cwseed",
    "type" : "free",
    "name" : "CW Seed",
    "regions" : [
      "US"
    ]
  },
  "source144" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hbo_prime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "HBO (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source288" : {
    "android_scheme" : "historyplus",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/history_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/history\/id576009463",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.aetn.history.watch",
    "ios_scheme" : "historyplus",
    "type" : "free",
    "name" : "The History Channel",
    "regions" : [
      "US"
    ]
  },
  "source355" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/disney_now_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/disneynow-shows-live-tv\/id529997671",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.disney.datg.videoplatforms.android.watchdc",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "DisneyNOW",
    "regions" : [
      "US"
    ]
  },
  "source380" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/funimation_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/funimation\/id1075603018",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.Funimation.FunimationNow",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Funimation",
    "regions" : [
      "US"
    ]
  },
  "source172" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/lifetime_movie_club_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Lifetime Movie Club (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source422" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/422_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "Flix Premiere",
    "regions" : [
      "US",
      "GB"
    ]
  },
  "source147" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hgtv_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "HGTV",
    "regions" : [
      "US"
    ]
  },
  "source214" : {
    "android_scheme" : "oxygentve",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/oxygen_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/oxygen-now\/id700797306",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.nbcu.tve.oxygen",
    "ios_scheme" : "oxygentve",
    "type" : "tve",
    "name" : "Oxygen",
    "regions" : [
      "US"
    ]
  },
  "source358" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hallmark_movies_now_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Hallmark Movies Now (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source383" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hbo_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "HBO",
    "regions" : [
      "US"
    ]
  },
  "source217" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/pbs_kids_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/pbs-kids-video\/id435138734",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=org.pbskids.video",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "PBS Kids",
    "regions" : [
      "US"
    ]
  },
  "source386" : {
    "android_scheme" : "hulu",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/386_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "hulu",
    "type" : "sub",
    "name" : "STARZ (Via Hulu)",
    "regions" : [
      "US"
    ]
  },
  "source101" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/docurama_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Docurama (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source7" : {
    "android_scheme" : "aetvplus",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/ae_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/a-e\/id571711580",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.aetn.aetv.watch",
    "ios_scheme" : "x-ae-services",
    "type" : "free",
    "name" : "A&E",
    "regions" : [
      "US"
    ]
  },
  "source178" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/mtv_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/mtv\/id422366403",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.mtvn.mtvPrimeAndroid",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "MTV",
    "regions" : [
      "US"
    ]
  },
  "source10" : {
    "android_scheme" : "abcplayer",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/abc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/abc-player\/id364191819",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.disney.datg.videoplatforms.android.abc",
    "ios_scheme" : "abcplayer",
    "type" : "tve",
    "name" : "ABC",
    "regions" : [
      "US"
    ]
  },
  "source270" : {
    "android_scheme" : "syfytve",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/syfy_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/syfy-now\/id378092432",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.nbcu.tve.syfy",
    "ios_scheme" : "syfytve",
    "type" : "tve",
    "name" : "Syfy",
    "regions" : [
      "US"
    ]
  },
  "source389" : {
    "android_scheme" : "peacock",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/peacockPremium_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "peacock",
    "type" : "sub",
    "name" : "Peacock Premium",
    "regions" : [
      "US"
    ]
  },
  "source13" : {
    "android_scheme" : "amcmobileapp",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/amc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amc-latest-full-episodes-extras\/id1025120568",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.amctve.amcfullepisodes",
    "ios_scheme" : "AMCTVOSAPP",
    "type" : "tve",
    "name" : "AMC",
    "regions" : [
      "US"
    ]
  },
  "source248" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/showtime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/showtime\/id996246479",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.showtime.standalone",
    "ios_scheme" : "showtime",
    "type" : "sub",
    "name" : "Showtime",
    "regions" : [
      "US"
    ]
  },
  "source315" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/wetv_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/we-tv-mobile-for-ipad\/id546812802",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.wetv.WEtviPhoneApp",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "WE tv",
    "regions" : [
      "US"
    ]
  },
  "source107" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/e_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/e!-now\/id876520365",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.nbcu.tve.e",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "E!",
    "regions" : [
      "US"
    ]
  },
  "source132" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/freeform_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/abc-family\/id505728417",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.disney.datg.videoplatforms.android.abcf",
    "ios_scheme" : "abcfamilyplayer",
    "type" : "tve",
    "name" : "Freeform",
    "regions" : [
      "US"
    ]
  },
  "source276" : {
    "android_scheme" : "watchtnt",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/tnt_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/watch-tnt\/id460494135",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.turner.tnt.android.networkapp",
    "ios_scheme" : "watchtnt",
    "type" : "tve",
    "name" : "TNT",
    "regions" : [
      "US"
    ]
  },
  "source19" : {
    "android_scheme" : "adultswim",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/adultswim_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/adult-swim\/id417871100",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.adultswim.videoapp.android",
    "ios_scheme" : "adultswim",
    "type" : "free",
    "name" : "Adult Swim",
    "regions" : [
      "US"
    ]
  },
  "source318" : {
    "android_scheme" : "wwe",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/wwe_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/wwe\/id551798799",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.wwe.universe",
    "ios_scheme" : "wwe",
    "type" : "sub",
    "name" : "WWE Network",
    "regions" : [
      "US"
    ]
  },
  "source135" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fuse_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/fuse-tv\/id967013714",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.fuse.fusetv",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Fuse",
    "regions" : [
      "US"
    ]
  },
  "source160" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/ifc_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "IFC",
    "regions" : [
      "US"
    ]
  },
  "source72" : {
    "android_scheme" : "ccnetworkapp",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/comedy-central\/id799551807",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.vmn.android.comedycentral",
    "ios_scheme" : "ccnetworkapp",
    "type" : "tve",
    "name" : "Comedy Central",
    "regions" : [
      "US"
    ]
  },
  "source371" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/appleTvPlus_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "AppleTV+",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source138" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/gaia_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Gaia (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source163" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/indie_flx_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "IndieFlix Shorts (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source349" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/apple_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "com.apple.TVShows",
    "type" : "purchase",
    "name" : "iTunes",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source374" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/betplus_primeVideo_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "BET+ (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source166" : {
    "android_scheme" : "ids-go",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/id_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id1101436941",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.discovery.idsgo",
    "ios_scheme" : "ids-go",
    "type" : "tve",
    "name" : "Investigation Discovery GO",
    "regions" : [
      "US"
    ]
  },
  "source191" : {
    "android_scheme" : "nbctve",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/nbc_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/nbc\/id442839435",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.nbcuni.nbc",
    "ios_scheme" : "nbctve",
    "type" : "free",
    "name" : "NBC",
    "regions" : [
      "US"
    ]
  },
  "source377" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/britbox_primeVideo_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "aiv-uk",
    "type" : "sub",
    "name" : "Britbox (Via Amazon Prime)",
    "regions" : [
      "GB",
      "US",
      "CA"
    ]
  },
  "source444" : {
    "android_scheme" : "pplus",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/paramountPlus_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "cbs",
    "type" : "sub",
    "name" : "Paramount+",
    "regions" : [
      "US",
      "AU",
      "CA"
    ]
  },
  "source169" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/logo_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/logotv\/id795019155",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.mtvn.logoandroid",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "LOGO",
    "regions" : [
      "US"
    ]
  },
  "source194" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/nbc_news_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/nbc-news\/id319740707",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.zumobi.msnbc",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "NBC News",
    "regions" : [
      "US"
    ]
  },
  "source303" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/vh1_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/vh1\/id413522634",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.mtvn.vh1android",
    "ios_scheme" : "vh1networkapp",
    "type" : "tve",
    "name" : "VH1",
    "regions" : [
      "US"
    ]
  },
  "source197" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/natgeo_wild100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "Nat Geo Wild",
    "regions" : [
      "US"
    ]
  },
  "source306" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/viceland_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/viceland\/id1075922366",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.vice.viceland",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "VICELAND",
    "regions" : [
      "US"
    ]
  },
  "source331" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hgtv_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/hgtv-watch\/id376038666",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.hgtv.watcher",
    "ios_scheme" : "hgtv-go",
    "type" : "tve",
    "name" : "Watch HGTV",
    "regions" : [
      "US"
    ]
  },
  "source24" : {
    "android_scheme" : "intent",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/amazon_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id545519333",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "purchase",
    "name" : "Amazon",
    "regions" : [
      "US",
      "GB",
      "AU",
      "CA"
    ]
  },
  "source267" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/sundance_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "onemainstream.MG9WJCOV",
    "type" : "tve",
    "name" : "Sundance",
    "regions" : [
      "US",
      "CA"
    ]
  },
  "source292" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/trvl_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : "trav-go",
    "type" : "free",
    "name" : "Travel Channel",
    "regions" : [
      "US"
    ]
  },
  "source27" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/ameba_prime_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Ameba (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source126" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fandor_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Fandor (Via Amazon Prime)",
    "regions" : [
      "US",
      "GB"
    ]
  },
  "source401" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/401_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "GuideDoc",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source151" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hallmark_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/hallmark-channel-everywhere\/id739360888",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.hallmarkchannel.awe",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "Hallmark Channel Everywhere",
    "regions" : [
      "US"
    ]
  },
  "source80" : {
    "android_scheme" : "crunchyroll",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/crunchyroll_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/crunchyroll-watch-anime-drama\/id329913454",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.crunchyroll.crunchyroid",
    "ios_scheme" : "crunchyroll",
    "type" : "sub",
    "name" : "Crunchyroll Premium",
    "regions" : [
      "US",
      "AU",
      "GB",
      "CA"
    ]
  },
  "source295" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/true_crime_files_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "True Crime Files by ID (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source55" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cmt_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/cmt-app\/id730993656",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.mtvn.cmtandroid",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "CMT",
    "regions" : [
      "US"
    ]
  },
  "source129" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/filmbox_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Filmbox Live (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source221" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/paramount_network_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/paramount-network\/id906788127",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.vmn.android.spike",
    "ios_scheme" : "paramountnetwork",
    "type" : "tve",
    "name" : "Paramount Network",
    "regions" : [
      "US"
    ]
  },
  "source298" : {
    "android_scheme" : "usatve",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/usa_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/usa-now\/id661695783",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.usanetwork.watcher",
    "ios_scheme" : "usatve",
    "type" : "free",
    "name" : "USA",
    "regions" : [
      "US"
    ]
  },
  "source365" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/imdb_tv_100px.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "free",
    "name" : "IMDB TV",
    "regions" : [
      "US"
    ]
  },
  "source86" : {
    "android_scheme" : "dam-go",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/dest_america_go_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/id1111281674",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.discovery.damgo",
    "ios_scheme" : "dam-go",
    "type" : "tve",
    "name" : "Destination America GO",
    "regions" : [
      "US"
    ]
  },
  "source157" : {
    "android_scheme" : "hulu",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/hulu_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/hulu-plus\/id376510438",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.hulu.plus",
    "ios_scheme" : "hulu",
    "type" : "sub",
    "name" : "Hulu",
    "regions" : [
      "US"
    ]
  },
  "source390" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/390_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "Hoopla",
    "regions" : [
      "US",
      "CA"
    ]
  },
  "source368" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/youtubePremium_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/youtube\/id544007664",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.google.android.youtube",
    "ios_scheme" : "youtube",
    "type" : "sub",
    "name" : "Youtube Premium",
    "regions" : [
      "US"
    ]
  },
  "source252" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/shudder_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/shudder-screams-on-demand\/id919790315",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.dramafever.shudder",
    "ios_scheme" : "onemainstream.A7TIV9SL",
    "type" : "sub",
    "name" : "Shudder",
    "regions" : [
      "US",
      "CA",
      "GB",
      "AU"
    ]
  },
  "source227" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/quello_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/amazon-instant-video\/id5455193",
    "android_playstore_url" : "http:\/\/amazon.com\/GetAndroidVideo",
    "ios_scheme" : "aiv",
    "type" : "sub",
    "name" : "Qello Concerts (Via Amazon Prime)",
    "regions" : [
      "US"
    ]
  },
  "source255" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/smithsonian_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/smithsonian-channel\/id482096908",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.smithsonian.android",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "Smithsonian Channel",
    "regions" : [
      "US"
    ]
  },
  "source322" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/diy_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/diy-watch\/id485756277",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.diy.watcher",
    "ios_scheme" : null,
    "type" : "tve",
    "name" : "Watch DIY Network",
    "regions" : [
      "US"
    ]
  },
  "source399" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/399_autogenerated.png",
    "ios_appstore_url" : null,
    "android_playstore_url" : null,
    "ios_scheme" : null,
    "type" : "sub",
    "name" : "FlixFling",
    "regions" : [
      "US",
      "CA"
    ]
  },
  "source114" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/fox_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/fox-now\/id571096102",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.fox.now",
    "ios_scheme" : "foxapp",
    "type" : "tve",
    "name" : "FOX",
    "regions" : [
      "US"
    ]
  },
  "source32" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/bbc_america_100px.png",
    "ios_appstore_url" : "itms-apps:\/itunes.apple.com\/us\/app\/bbc-america\/id1089249069",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.bbca.bbcafullepisodes",
    "ios_scheme" : "bbcatvapp",
    "type" : "tve",
    "name" : "BBC America",
    "regions" : [
      "US"
    ]
  },
  "source35" : {
    "android_scheme" : null,
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/bet_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/bet-now-watch-shows\/id841118013",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.bet.shows",
    "ios_scheme" : null,
    "type" : "free",
    "name" : "BET",
    "regions" : [
      "US"
    ]
  },
  "source63" : {
    "android_scheme" : "cartoonnetwork",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/cn_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/watch-cartoon-network-videos\/id404593641",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.turner.cnvideoapp",
    "ios_scheme" : "cartoonnetwork",
    "type" : "free",
    "name" : "Cartoon Network",
    "regions" : [
      "US"
    ]
  },
  "source353" : {
    "android_scheme" : "watchtrutv",
    "logo_100px" : "https:\/\/cdn.watchmode.com\/provider_logos\/trutv_100px.png",
    "ios_appstore_url" : "http:\/\/itunes.apple.com\/app\/watch-trutv\/id396972659",
    "android_playstore_url" : "https:\/\/play.google.com\/store\/apps\/details?id=com.turner.trutv",
    "ios_scheme" : "watchtrutv",
    "type" : "tve",
    "name" : "truTV",
    "regions" : [
      "US"
    ]
  }
}

const getSourceDetails = (sourceId => {
  let source = sources['source' + parseInt(sourceId)];
  source.id = parseInt(sourceId)

  return source;
})

module.exports.getSourceDetails = getSourceDetails;