name: Node Continuous Integration

on:
  pull_request:
    branches: [ staging ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: npm ci
      - run: npm run react-test
      - run: CI=false npm run build