name: Node Continuous Integration

on:
  pull_request:
    branches: [ staging ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}
      PORT: ${{ secrets.PORT }}
      WATCHMODE_API_KEY: ${{ secrets.WATCHMODE_API_KEY }}
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: npm ci
      - run: npm run react-test
      - run: npm run back-test
      - run: CI=false npm run build